allowBuilds:
  '@astryxdesign/cli': false
  '@astryxdesign/core': false
  esbuild: true
  workerd: true
supportedArchitectures:
  os:
    - current
  cpu:
    - current
    - x64
minimumReleaseAgeExclude:
  - miniflare@5.20260910.0-alpha
  - wrangler@4.131.0
