allowBuilds:
  '@astryxdesign/cli': true
  '@astryxdesign/core': true
  esbuild: true
  workerd: true
supportedArchitectures:
  os:
    - current
  cpu:
    - current
    - x64
minimumReleaseAgeExclude:
  - miniflare@5.20260910.0-alpha
  - wrangler@4.131.0
  - '@astryxdesign/core@0.6.3'
  - '@astryxdesign/theme-neutral@0.6.3'
  - '@astryxdesign/cli@0.6.3'
